// programa CONDICAO7
inicio
  variavel texto N1, N2
  variavel caracter S1, S2
  escrever "Entre nome do 1o. dançarino: "
  ler N1
  escrever "Entre sexo do 1o. dançarino: "
  ler S1
  escrever "Entre nome do 2o. dançarino: "
  ler N2
  escrever "Entre sexo do 2o. dançarino: "
  ler S2
  se (S1 = "M") xou (S2 = "M") entao 
    escrever N1, " pode dançar com ", N2
  senao
    escrever N1, " não pode dançar com ", N2
  fimse
fim
